---

github_branch: master
github_user: linuxserver
templated_vars:
 - 'jenkins-vars.yml'
 - 'readme-vars.yml'
project_blurb_optional_extras_enabled: false
project_blurb_optional_extras: []
available_architectures: []
development_versions: false
development_versions_items: []
# PGID, PUID
common_param_env_vars_enabled: true
param_usage_include_net: false
param_net: ""
privileged: false
cap_add_param: false
cap_add_param_vars: []
opt_cap_add_param: false
opt_cap_add_param_vars: []
security_opt_param: false
security_opt_param_vars: []
opt_security_opt_param: false
opt_security_opt_param_vars: []
param_usage_include_hostname: false
param_hostname: ""
param_usage_include_mac_address: false
param_mac_address: ""
param_usage_include_env: false
param_env_vars: []
opt_param_usage_include_env: false
opt_param_env_vars: []
param_usage_include_vols: false
param_volumes: []
opt_param_usage_include_vols: false
opt_param_volumes: []
param_usage_include_ports: false
param_ports: []
opt_param_usage_include_ports: false
opt_param_ports: []
param_device_map: false
param_devices: []
opt_param_device_map: false
opt_param_devices: []
app_setup_block_enabled: false
app_setup_block: ""
external_application_snippet_enabled: false
external_application_cli_block: ""
external_application_compose_block: ""
external_application_unraid_block: ""
optional_block_1: false
changelogs: []
custom_external_trigger: ""
custom_package_trigger: ""
external_trigger_delay_hours: 0
unraid_template_sync: true
unraid_template: true
armhf_native: false
build_armhf: false
image_provenance: true
image_sbom: true
