---

templated_files:
 - { src: 'README.j2', dest: 'README.md' , readme: 'true' }
 - { src: 'lite.j2', dest: 'README.lite' , readme: 'true' }
 - { src: 'DOCUMENTATION.j2', dest: "{{ github_project_name }}.md" , readme: 'true' }
 - { src: 'Jenkinsfile.j2', dest: 'Jenkinsfile' }
 - { src: 'LICENSE.j2', dest: 'LICENSE' }
 - { src: 'FUNDING.j2', dest: '.github/FUNDING.yml' }
 - { src: 'ISSUE_TEMPLATE.j2', dest: '.github/ISSUE_TEMPLATE.md' }
 - { src: 'PULL_REQUEST_TEMPLATE.j2', dest: '.github/PULL_REQUEST_TEMPLATE.md' }
 - { src: 'DONATE.j2', dest: 'root/donate.txt' , donate: 'true' }
 - { src: 'greetings.j2', dest: '.github/workflows/greetings.yml' }
 - { src: 'stale.j2', dest: '.github/workflows/stale.yml' }
 - { src: 'CONTRIBUTING.j2', dest: ' .github/CONTRIBUTING.md' }
