---
templated_files:
  - { src: '.editorconfig.j2', dest: '.editorconfig' }
  - { src: '99-deprecation.j2', dest: 'root/etc/s6-overlay/s6-rc.d/init-deprecate/run', deprecation: 'true' }
  - { src: 'CONTRIBUTING.j2', dest: '.github/CONTRIBUTING.md' }
  - { src: 'DOCUMENTATION.j2', dest: '.jenkins-external/{{ project_repo_name }}.md' , readme: 'true' }
  - { src: 'DONATE.j2', dest: 'root/donate.txt' , donate: 'true' }
  - { src: 'EXTERNAL_TRIGGER_SCHEDULER.j2', dest: '.github/workflows/external_trigger_scheduler.yml' }
  - { src: 'EXTERNAL_TRIGGER.j2', dest: '.github/workflows/external_trigger.yml', external_trigger: 'true' }
  - { src: 'FUNDING.j2', dest: '.github/FUNDING.yml' }
  - { src: 'greetings.j2', dest: '.github/workflows/greetings.yml' }
  - { src: 'ISSUE_TEMPLATE.bug.j2', dest: '.github/ISSUE_TEMPLATE/issue.bug.yml' }
  - { src: 'ISSUE_TEMPLATE.config.j2', dest: '.github/ISSUE_TEMPLATE/config.yml' }
  - { src: 'ISSUE_TEMPLATE.feature.j2', dest: '.github/ISSUE_TEMPLATE/issue.feature.yml' }
  - { src: 'Jenkinsfile.j2', dest: 'Jenkinsfile' }
  - { src: 'LICENSE.j2', dest: 'LICENSE' }
  - { src: 'lite.j2', dest: '.jenkins-external/README.lite' , readme: 'true' }
  - { src: 'PACKAGE_TRIGGER_SCHEDULER.j2', dest: '.github/workflows/package_trigger_scheduler.yml' }
  - { src: 'PULL_REQUEST_TEMPLATE.j2', dest: '.github/PULL_REQUEST_TEMPLATE.md' }
  - { src: 'README.j2', dest: 'README.md' , readme: 'true' }
  - { src: 'UNRAID_TEMPLATE.j2', dest: '.jenkins-external/{{ project_name | lower }}.xml' , unraid_template: 'true' }
  - { src: 'CALL_ISSUE_PR_TRACKER.j2', dest: '.github/workflows/call_issue_pr_tracker.yml' }
  - { src: 'permissions.j2', dest: '.github/workflows/permissions.yml' }
  - { src: 'CALL_WORKFLOW_ISSUES_CRON.j2', dest: '.github/workflows/call_issues_cron.yml' }
